#需要屏蔽的指令列表
blockCommand:
  #针对OP是否启用指令屏蔽
  bypassOP: true
  #执行屏蔽指令时的返回信息，支持 & 开头颜色代码
  blkMsg: "&eCommand not found!"
  commands:
    - plugins
    - ?
    - help
    - pl
    - about
    - version
    - ver
    - bukkit:?
    - bukkit:pl
    - bukkit:about
    - bukkit:version
    - bukkit:ver
    - bukkit:help
    - bukkit:plugins
    - minecraft:pl
    - minecraft:plugins
    - minecraft:about
    - minecraft:version
    - minecraft:ver
    - minecraft:help

rtp:
  enable: true
  #随机传送范围，x，y共用最大值，+max-range 至 -max-range 范围之间
  max-range: 2000
  #rtp传送要排除的不安全方块类型
  unsafe-blocks:
    - WATER
    - LAVA
    - AIR




