name: NoPluginsCommand
version: 1.4
main: net.noodles.pl.nopluginscommand.NoPluginsCommand
authors: [BGHDDevelopmentLLC]
description: Blocks /plugin, /about, /version, and add /rtp, /home, /spawn!
website: https://bghddevelopment.com
api-version: 1.21.1

commands:
  rtp:
    description: 随机传送
    usage: /<command>

  home:
    description: 传送到复活点
    usage: /<command>

  spawn:
    description: 传送到服务器出生点
    usage: /<command>